version: '3.7'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '9000:9000'
    command: npm run dev
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '8000:8000'
    command: npm start
volumes:
  backend:
  frontend:
